spring: 
  mvc:
    static-path-pattern: /static/**
    
server:
  port: 8080  # Spring boot Server port
  servlet:
    context-path: /
    
logging:
  config: classpath:log4j2-product.xml
  level:
    root: info  
    com.hj.hjnf.gwsvc: DEBUG